### ISSUE TITLE
Unable to use MQTT integration with HiveMQ?

### ISSUE THREAD

**Issue by johnconn73** [helium/console#996] opened 2022-01-18 09:07 UTC
HiveMQ cloud MQTT uses TLS (or websockets and TLS) on ports 8883 or 8884.  I've tried to use the MQTT integration in Console and configured with mqtts://username:password@hostname:port as the endpoint, but it doesn't work. The only error I get is "The Integration is unsuccessful. Check the Integration for details."  There's nothing obviously wrong. I've tested the same flow to an MQTT server without TLS and it worked fine.  Not sure whether the issue is HiveMQ or TLS specific... Ta.

**Comment by takeabyte** [comment] 2022-01-18 16:15
Adafruit.io mqtt integration also fails. Port 1883 and 8883 both throw an integration error. Switching to my integration directly via menu integrations > my-adafruit-mqtt all fields are blank first time until refresh.

**Comment by jdgemm** [comment] 2022-01-18 16:36
closing this issue as it's a duplicate of https://github.com/helium/router/issues/579

**Closed by jdgemm** 2022-01-18 16:36 UTC
