### ISSUE TITLE
Console Organization hierarchical features request

### ISSUE THREAD

**Issue by wprojects** [helium/console#997] opened 2022-01-19 19:00 UTC
My team has been going through the console organization features and has noticed there are some limitations to the consoles features as far as interacting with other organizations. For example, our company is going to be doing events such as hackathons or developer programs where we will be sponsoring/supporting developers and students building on the Helium network. Currently from what we have seen, we have only been able to invite a user to our organization, and that user can basically see our console and can access it that way or vice versa. We noticed that you would be able to transfer data credits this way, but it will not be ideal for a larger umbrella of organizations. The idea would be that you could create an umbrella tree systems for organizations to interact with other organizations as a parent/child relationship so that we could send them data credits and what not without having to actually be in their organization. Another cool feature would be where child organizations under the parent could request data credits or help with whatever is needed. This way we could open a page in the console, and be able to manage and check each organizations data credits and be able to refill when necessary or request to step in and help. 

Let me know if you guys have some information I am not aware of that could help us with this situation, or have any questions about adding a feature like this! Thanks

**Comment by jdgemm** [comment] 2022-01-26 20:03
Thanks for your feedback and suggestions. 

What is preventing you from using the current organization structure, and adding only relevant users to those orgs? You can manage which users have access to which orgs. This way you still have "child" organizations and accomplish what you've listed:
- access their org, help when needed
- transfer data credits

By design Data Credits are not transferrable so transferring Data Credits is only permitted among organizations the Data Credit owner belongs to. 

At this time, additional hierarchy is not something we plan on supporting for Console.

**Closed** 2022-02-04 00:29 UTC
